services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - api-gateway

  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - notes-service
      - summarizer-service

  notes-service:
    build: ./backend/notes-service
    ports:
      - "8001:8001"

  summarizer-service:
    build: ./backend/summarizer-service
    ports:
      - "8002:8002"
    environment:
      - OPENAI_API_KEY=your_openai_api_key

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - api-gateway
